### ISSUE TITLE
Add optional path args to various commands

### ISSUE THREAD

**Issue by nwmcsween** [metio/terraform-provider-git#28]
example
```
resource "git_repository "repo" {
  directory = "git/dir"
}

resource "git_commit" "commit" {
  directory = data.ggit_repository.repo.directory
  commit = "latest"
  path = "path/in/git"
}
```

sha1 -> commit attr

**Comment by sebhoss** [comment]
hey thanks for opening a ticket!

I just did something related to your example that looks like this:

```
resource "git_repository "repo" {
  directory = "git/dir"
}

resource "git_commit" "commit" {
  directory = data.git_repository.repo.directory
  sha1      = data.git_repository.repo.sha1
}
```

with `git_repository.sha1` being the SHA1 of the current `HEAD` in the repository. I've added a small example at https://github.com/metio/terraform-provider-git/blob/main/tests/data_source_git_comit.tf as well that shows this. Since naming stuff is always hard, I picked sha1 over commit in the past because I wanted to support SHA256 as well once that gets added to go-git.

The addition of the `sha1` attribute to `git_repository` is in this repository but not yet released, therefore it can still be changed (or renamed) - wdyt?

About the `path` attribute: Do you want to fetch the commit infos related to a single file/directory in a git repository?

**Comment by nwmcsween** [comment]
With regards to sha1 if you would ever want to use symbolic hashes at any point (latest, HEAD~1, etc) then `commit` would be easier to reason about.

The `path` attribute would do as you wrote but having a path and a `directory` attribute would be confusing without reading documentation.

**Comment by sebhoss** [comment]
Yep that's a good point - I've used the hash originally because that's what go-git expects when calling `repository.CommitObject(...)`, however it's possible to convert a given revision to a hash first in order to allow stuff like `HEAD~1` as well. I'm going to use `revision` instead of `commit` in order to mirror the naming from https://www.git-scm.com/docs/gitrevisions.

Wrt. `path` I'm currently prototyping a `git_log` data source that has a `filter_paths` attribute (list of strings) and works like this:

```
data "git_log" "custom_logs" {
  directory    = data.git_repository.repository.directory
  filter_paths = ["tests/*"]
  from         = "HEAD"
  max_count    = 5
}

data "git_commit" "from_log" {
  for_each  = toset(data.git_log.custom_logs.commits)
  directory = data.git_repository.repository.directory
  revision  = each.value
}
```

I want to keep using `directory` because that's what it's called in https://git-scm.com/docs/git-init and I want to make sure that everyone understands that this provider only works on local git repositories and inputs like `github.com:org/repo.git` are not supported. Additionally I think that using a different name for the same value across multiple resources/data sources is confusing.

**Comment by nwmcsween** [comment]
Works for me, copying naming from code makes it easy to reason about.

**Comment by sebhoss** [comment]
both changes are in main and will be released on 2022-08-26 automatically.

**Comment by sebhoss** [comment]
Released with https://github.com/metio/terraform-provider-git/releases/tag/2022.8.26
